"""Create gig table

Revision ID: 5dd6946db34a
Revises: 
Create Date: 2023-06-22 19:00:31.267711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dd6946db34a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gig',
    sa.Column('no', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('info', sa.String(length=500), nullable=False),
    sa.Column('UpAcc', sa.String(length=3), nullable=False),
    sa.Column('NatureOfWork', sa.String(length=100), nullable=False),
    sa.Column('Cost', sa.String(length=50), nullable=False),
    sa.Column('Status', sa.String(length=100), nullable=False),
    sa.Column('DateCreated', sa.String(length=80), nullable=True),
    sa.Column('DateCompleted', sa.String(length=80), nullable=True),
    sa.Column('OrderNumber', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gig')
    # ### end Alembic commands ###
